/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107338-gf9785a78da-20220709"
#endif /* AVUTIL_FFVERSION_H */
